Sergiy.simchuk/in work
Artya/CSharp33 pull request #8
Opened 2021-12-02 21:42 UTC by SergiySimchuk

Lets go!

2021-12-02 21:45 UTC, SergiySimchuk commented on FarmerWolfGoatCabbage/FarmerWolfGoatCabbage/Program.cs
> +            ShowBanksState(farmerOnLeftBank, wolfOnLeftBank, goatOnLeftBank, cabbagOnLeftBank);
Не подумав шо методи не можна використовувати раз ми їх не вчили.

2021-12-02 21:59 UTC, araka86 submitted a review, later dismissed
🔥 👍

2021-12-03 07:17 UTC, kievzenit approved these changes
Апрувлю sln'ки и прочие вспомогательные файлы

2021-12-03 07:18 UTC, kievzenit requested changes

2021-12-03 07:18 UTC, kievzenit commented on Factorial/Factorial/Program.cs
> +            if (number > 1)
Здесь не согласен, факториал может быть от нуля, 0! = 1, надо добавить

2021-12-03 07:45 UTC, SergiySimchuk commented on Factorial/Factorial/Program.cs
> +            if (number > 1)
Якщо користувач введе нуль  або одиницю програма поверне йому в результаті 1, бо конструкція if (number > 1) поверне false, а отже змінна int result лишиться  = 1, нема потреби явно прописувати обробку кейса нуль в коді, я вважаю.

2021-12-03 07:46 UTC, kievzenit commented on Factorial/Factorial/Program.cs
> +            if (number > 1)
Всё, понял, тогда согласен

2021-12-03 07:46 UTC, kievzenit approved these changes

2021-12-03 08:40 UTC, araka86 approved these changes

2021-12-03 21:19 UTC, Artya requested changes
Please separate tasks by branches, because here we have a mess

2021-12-03 21:19 UTC, Artya commented
For each task please create separate PR

2021-12-03 23:00 UTC, SergiySimchuk commented
Ok. I`ll divide this fat branche to different tasks. I didn`t know every task needs separate branche. 
I think, it was beta pull request )))

2021-12-03 23:00 UTC, closed without merging